### ISSUE TITLE
Char module and FFI

### ISSUE THREAD

**Issue by rascala** [kjnilsson/fez#16]
Hi,

I have been working on a rudimentary System.Char module.
But the method names are all capitalized.
I have uncapitalized(?) them for now, but that raises a question.

Do we have any ideas on an FFI for this?
It would also solve the string() operator issue  #6 (dispatch to different functions with same arity but different type signatures) without having to make it a special case in the compiler.

**Comment by forki** [comment]
I personally think compiler should handle decapitalizing

**Comment by kjnilsson** [comment]
@rascala can you raise an early PR so I can see how you've been approaching it?

**Comment by kjnilsson** [comment]
this code `System.Char.IsDigit '1'` will generate the following core erlang:
```
call 'System.Char':'IsDigit'($1)
```

which means you need to implement an erlang module named `'System.Char'` (note single quotes) with a function named `'IsDigit'` taking a single argument.

**Comment by rascala** [comment]
Hadn't done that!
It seems to work fine now.
Thanks

**Comment by kjnilsson** [comment]
We need to have a discussion on whether / which `System.*` modules should be part of the core compiler or should ship as an optional library but for now just stick implementations into `src` like all the others.

**Comment by kjnilsson** [comment]
Modules like `System.Char` that refer to core types should probably go in here. At least the static methods and non-mutable apis.
