### ISSUE TITLE
Current Definition of Option Type

### ISSUE THREAD

**Issue by Lleutch** [kjnilsson/fez#20]
I have seen that the current implementation of the option type in the erlang modules is defined as follow : 

` -type option() :: term() | undefined.`

I do understand that you want options to be erased however when I then see the implementation of the get method : 

```
get(O) when O =/= undefined ->
    O.
```

Then for me the type is more : 
    `-spec get(option()) -> option()` 
than what is specified which was :  
    `-spec get(option()) -> term().`

Is there something I am missing there?

P.S : 
What I would have thought was to design the option type as a couple as follow :
`-type option() :: {some, term()} | undefined`

**Comment by kjnilsson** [comment]
Not sure you can write an accurate typespec for that function. term() ->
term() is probably the closest.

**Comment by kjnilsson** [comment]
There are good reasons for keeping the current erlang representation of `option`. Using `undefined` to signify a missing value (like `None` or `null`) is ubiquitous in erlang which means this will interoperate well. See eg. https://github.com/kjnilsson/fez/blob/master/test/basics.fs#L349

Cheers
Karl
