### ISSUE TITLE
Alpaca

### ISSUE THREAD

**Issue by ShalokShalom** [kjnilsson/fez#25]
> The primary aim is to implement enough of the language to evaluate what how well an ML type of language could become a practical language for writing code to be run on the beam.

https://github.com/alpaca-lang/alpaca

**Comment by kjnilsson** [comment]
Thanks. I’m well aware of alpaca. The approach is different. Alpaca is a from the ground creation. Fez taps into a mature language and tooling ecosystem. Cheers.

**Comment by ShalokShalom** [comment]
You like to point this out officially?

**Comment by forki** [comment]
@shalomshalom? Why? And where? This is completely unrelated.

**Comment by ShalokShalom** [comment]
The current text is misleading. 

> 
The primary aim is to implement enough of the language to evaluate what how well an ML type of language could become a practical language for writing code to be run on the beam.

This is already implemented and through that evaluated, yes?

**Comment by forki** [comment]
I personally think it's not misleading. But sure you can always interpret
things differently.

Am 25.12.2017 18:44 schrieb "MatthiasSchuster" <notifications@github.com>:

**Comment by kjnilsson** [comment]
I think the question about how well an ML could work on the beam is still unanswered and may never be answered by this particular project. But perhaps the project mission statement needs to be refined. In as much as something that started as an extended hack needs a mission statement at all.

We'll see what comes out of the next couple of months. Thanks for your input.
