### ISSUE TITLE
string() operator should only work for non-strings

### ISSUE THREAD

**Issue by rascala** [kjnilsson/fez#6]
Hi,

There is a mismatch between the behaviour in fsharpi and fez for the string() operator.
fsharpi does not escape and stringify if the input is string("abc" -> "abc"), but fez does("abc" -> "\\"abc\\"").

Looks like we can't call different functions based on the type signature as the erlang wrappers don't have access to the types.(or can we?). And even if we could switch based on types, data received from other erlang processes wouldn't have that info, so are they supposed to be strings or just happen to be printable?

I have an implementation of string() which uses printable_unicode_list() and printable_list() and does not re-stringify them.
Should we go with that for now?

-- Siddarth

**Comment by kjnilsson** [comment]
Hi,

I take it you are talking about https://github.com/kjnilsson/fez/blob/master/src/Microsoft.FSharp.Core.Operators.erl#L47 ?

We probably should special case `string(_)` in the compiler where we have type information available then default back to this method for non-primitive types. Alternatively we can implemented `ToString` on `System.String` in erlang and delegate to this as other types may want to override `ToString` and we could just use the `trait_call` mechanism to dispatch to these.  It's not a straight-forward thing to handle however as it involves emulating object hierarchies.

**Comment by kjnilsson** [comment]
pushed special case handling for this: https://github.com/kjnilsson/fez/blob/master/src/fez/Compiler.fs#L487

**Comment by rascala** [comment]
Aah, so the old implementation of string() should work?
I will have to undo my changes and test the Char module again.

Will make a pull request once tests pass

**Comment by rascala** [comment]
I think the chars are also a special case, otherwise the string() will return a stringified number
string 'a' -> ["97"]

**Comment by kjnilsson** [comment]
Well it will never work quite the same as for fsharp but not sure what we
can do without subtype dispatching.

**Comment by rascala** [comment]
Hmm, well I'll comment out that one test which needs that behaviour.
Lets revisit this later.

I'll make a pull request for the Char module for now.
