### ISSUE TITLE
Allow to set out folder in fezc

### ISSUE THREAD

**Issue by forki** [kjnilsson/fez#8]

**Comment by kjnilsson** [comment]
I think the way forward here is to add options to `fez` itself. How about:

```
fez compile <opts> -- <files>
```

Opts:

--beam | --core // output format with core being default
--output // output dir 
--ast // outputs a .ast file with the fsharp ast as well
--emit-core-paths // only core file paths are written to stdout - for piping into erlc 

What is a good options parser these days?

**Comment by Lleutch** [comment]
Well as an option parser for CLI options in F# I would have used Argu : https://fsprojects.github.io/Argu/

**Comment by kjnilsson** [comment]
Argu looks good thanks.
